### PR TITLE
Add YDN

### PR DESCRIPTION
**Pull request by kevinprince**

### CODE REVIEW

**Comment by leeky** [comment]
Why is your PR also removing EE from the home page, but not the sponsors page? Otherwise, :ok:

**Comment by mseckington** [comment]
Maybe we should merge this in; Yahoo have confirmed, right? 

And yeah, I repeat what Leeky asked: why is the Equal Experts logo being removed from the home page?

**Comment by leeky** [comment]
:+1: Go! Go! Go!

**Comment by kevinprince** [comment]
Need Y! to sign off still, hopefully today.

**Pull request merged**
